Много всякого
JustAGod1/bevm pull request #6
Opened 2023-04-27 23:16 UTC by AndrewKraevskii

- Удалена библиотека nom вместо неё ручной парсинг.
- Замена макросов на функции в тех случаях когда это не несёт никакой пользы
- Использование более современного синтаксиса для распаковки Optional
- Убрано ручное индексирование в циклах for
- Смена библиотеки для открытия файлов на более современную 
- Теперь файлы можно сохранять под любыми названиями а не только generic.mm
- Исправлен краш программы при переполнении переменной (теперь там явно указано что переполнение желанное поведение)
- [target.x86_64-pc-windows-msvc] передвинут в config.toml
- Код форматирован с использованием cargo fmt
- Большинство предупреждений исправлено или указано явно их игнорировать
- cargo clippy предупреждения тоже исправлены

2023-04-27 23:32 UTC, AndrewKraevskii commented
Также теперь при запуске в debug режиме показывается консоль. Иначе rust не выводит ошибки

2023-04-28 00:35 UTC, JustAGod1 requested changes
Вроде все просмотрел. Но вот штуку с prev_prev_zero надо б все-таки вернуть.

2023-04-28 00:35 UTC, JustAGod1 commented on src/ui/cells.rs
> +            .add_filter("", &["mm"])
ну если мы добрые и хотим разрешить сохранять как хочется, то можно б и добавить абилку сохранять с любым расширением

2023-04-28 00:35 UTC, JustAGod1 commented on src/ui/cells.rs
> +                if prev_zero {
prev_prev_zero все-таки имеет некоторый смысл. 
если написать код
```
ISZ 5
ISZ 0
ISZ 6
```

в этой реализации оно запишется как
```
$pos 0
ISZ 005
$pos 2
ISZ 006
```

Основная идея добавлять `pos` в файл сохранения это беречь место, но в этом случае мы не экономим примерно ничего и вероятно ухудшаем читаемость если `ISZ 0` имело какой-то смысл, что обычно правда когда оно находится между какими-то другими командами.

2023-04-28 00:39 UTC, JustAGod1 commented
Спасибо за пулл реквест. Так видимо и буду учить расть.  
Новые паттерн матчинги выглядят сексуально.  
Зачем нужно было заменять парсинг на ручной мне не очень понятно. Я б заменил на chumsky или типа того, но соглашусь то как оно было до этого не может нравится адекватному человеку. Хоть и ручной парсинг не кажется адекватным решением, но видимо пусть будет так.
Выбор файла, а не папки, конечно, супер полезно.

2023-04-28 00:43 UTC, JustAGod1 commented
а ладно минуточка осознания, что prev_prev_zero никогда не обновлялся

2023-04-28 00:43 UTC, merged

2023-04-28 00:45 UTC, JustAGod1 commented on src/ui/cells.rs
> +                if prev_zero {
я сам дурак

2023-04-28 00:48 UTC, AndrewKraevskii commented
> а ладно минуточка осознания, что prev_prev_zero никогда не обновлялся 

Я на самом деле обнаружил эту ошибку потому что компилятор раста сказал что она никогда не используется)

2023-04-28 00:53 UTC, AndrewKraevskii commented
Честно в логике работы самого evm не разбирался (слишком страшно), так что изменения довольно поверхностные.

2023-04-28 01:01 UTC, AndrewKraevskii commented
> Зачем нужно было заменять парсинг на ручной мне не очень понятно. Я б заменил на chumsky или типа того, но соглашусь то как оно было до этого не может нравится адекватному человеку. Хоть и ручной парсинг не кажется адекватным решением, но видимо пусть будет так.

Я когда смотрел код подумал что раз использование так лимитировано то почему бы и ручками не написать. Не планировал делать pull request так что просто попрактиковался в test driven development. Было давно так что я сам хз для чего сделал